# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileDi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileDi
	pod 'Toast-Swift'
    pod 'SwiftLoader'
    pod 'Alamofire', '~> 4.4'
    pod 'SideMenu', '~> 2.2'
    pod 'Cosmos'
    pod 'SDWebImage'
end
